## init
default['rsyslog_app']['facility'] = 'local2'
default['rsyslog_app']['virtual_host'] = '/'
default['rsyslog_app']['host'] = '127.0.0.1'
default['rsyslog_app']['user'] = 'guest'
default['rsyslog_app']['password'] = 'guest'
default['rsyslog_app']['template'] = 'RSYSLOG_FileFormat'
default['rsyslog_app']['routing_key'] = 'app'
default['rsyslog_app']['timeoutenqueue'] = '0'
default['rsyslog_app']['highwatermark'] = '12000000'
default['rsyslog_app']['lowwatermark'] = '400000'
default['rsyslog_app']['discardmark'] = '16000000'
default['rsyslog_app']['maxdiskspace'] = '5g'
default['rsyslog_app']['queuesize'] = '20000000'
default['rsyslog_app']['saveonshutdown'] = 'on'
default['rsyslog_app']['resumeretrycount'] = '-1'
